defaults:
  user: your.username  # edit this to your Jira username
  hours: 12
  env: prod

profiles:
  # ── C9 ──────────────────────────────────────────────────
  c9-prod:
    provider: foxpass
    group: c9prod-sre-breakglass

  # ── Symphony - Legacy Salt ──────────────────────────────
  salt-prod:
    provider: foxpass
    group: foxpass_sre_temp

  # ── Symphony - GKE ──────────────────────────────────────
  prod-cluster:
    provider: gcp
    group: sym-sso-gcp-cluster-breakglass
    project: sym-prod-use4-gke-01
    namespace: unused

  prod-datastore:
    provider: gcp
    group: sym-sso-gcp-datastore-breakglass
    project: sym-prod-mr-tools-01
    namespace: unused

  prod-secrets:
    provider: gcp
    group: sym-sso-gcp-sbe-admin-breakglass
    project: sym-prod-use4-data-01
    namespace: unused

  uat-secrets:
    provider: gcp
    group: sym-sso-gcp-sbe-admin-breakglass
    project: sym-uat-use4-data-01
    namespace: unused
    env: uat

  # ── TLM / Entra ─────────────────────────────────────────
  tlm-prod:
    provider: entra
    group: PMP_DUO_SRE_PROD_BR

  tlm-uat:
    provider: entra
    group: PMP_DUO_SRE_UAT_BR
    env: uat
